version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "5001:80"
    volumes:
      - ./dist/templates:/usr/share/nginx/templates
      - ./dist/static:/usr/share/nginx/static
      - ./default.conf:/etc/nginx/conf.d/default.conf